# Generated by Django 3.0.6 on 2020-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='name of article')),
                ('article_text', models.TextField(verbose_name='content of article')),
                ('pub_date', models.DateTimeField(verbose_name='date of article publication')),
            ],
        ),
    ]
